### ISSUE TITLE
ImportError: No module named bs4

### ISSUE THREAD

**Issue by marclundgren** [nmar/craigslist-scraper#1]
maybe I'm running the script wrong

```
➜  craigslist-scraper git:(master) ✗ python clstates.py
Traceback (most recent call last):
  File "clstates.py", line 1, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4
```

**Comment by nmar** [comment]
Hey Marc - I think you're either running an older version of python or have not installed Beautiful Soup...

**Comment by marclundgren** [comment]
```
Python 2.7.6
```

```
sudo pip install bs4
Password:
Downloading/unpacking bs4
  Could not find any downloads that satisfy the requirement bs4
Cleaning up...
No distributions at all found for bs4
```

**Comment by marclundgren** [comment]
```
which bs4
bs4 not found
```

**Comment by marclundgren** [comment]
that's probably why

**Comment by monajalal** [comment]
You should install bs4 using easy_install. I did it like so:
sudo su
easy_install BeautifulSoup4

**Comment by 5j9** [comment]
The correct command to [install Beautiful Soup 4](http://www.crummy.com/software/BeautifulSoup/bs4/doc/#installing-beautiful-soup) is `pip install beautifulsoup4`, not `pip install bs4`.

**Comment by polyakoff** [comment]
@5j9 Thank you!
